In [2]:
from keras.datasets import imdb
from keras.models import Model
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Input , Embedding , SimpleRNN , Dense , LSTM , Bidirectional

max_features = 25000 # Only top 25000 unique words or features
maxlen = 250 # Consider only the the first 250 words for each movie review

In [3]:
# Loading and Splitting the data
(x_train,y_train) , (x_val,y_val) = imdb.load_data(num_words=max_features)

print(len(x_train), "Training Sequences")
print(len(x_val), "Validation Sequences")

# Applying post padding on the data
# Truncate the sequences from the end longer than 250 words
# Apply Zero padding to the end words shorter than 250 words
x_train = pad_sequences(x_train,padding='post',truncating='post',maxlen=maxlen)
x_val = pad_sequences(x_val,padding='post',truncating='post',maxlen=maxlen)


25000 Training Sequences
25000 Validation Sequences


In [10]:
inputs = Input(shape=(None,),dtype="int32")

# Embedding layer , Embed each integer to 128-dimensional vector
x = Embedding(max_features,128)(inputs)

# Adding 3 SimpleRNN layer
x = Bidirectional(LSTM(64,return_sequences=True))(x)
x = Bidirectional(LSTM(64,return_sequences=True))(x)
x = Bidirectional(LSTM(64))(x)

# Adding a classifier
outputs = Dense(5,activation='softmax')(x)
model = Model(inputs,outputs)

model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None)]            0         
                                                                 
 embedding (Embedding)       (None, None, 128)         3200000   
                                                                 
 bidirectional (Bidirection  (None, None, 128)         98816     
 al)                                                             
                                                                 
 bidirectional_1 (Bidirecti  (None, None, 128)         98816     
 onal)                                                           
                                                                 
 bidirectional_2 (Bidirecti  (None, 128)               98816     
 onal)                                                           
                                                            

In [12]:
import numpy as np
x_pract = x_train[:10]
predicted_binary_ratings = model.predict(x_pract)

print("Binary_rating ")
print(predicted_binary_ratings)
# Convert binary predictions to integer values between 1 and 5
predicted_ratings = np.argmax(predicted_binary_ratings, axis=1) + 1

# Print the first few predicted ratings
print("Rating")
print(predicted_ratings)

1/1 [==============================] - 2s 2s/step
Binary_rating 
[[0.19746864 0.20052773 0.19793393 0.20323306 0.20083661]
 [0.1981381  0.2009239  0.19791187 0.20280226 0.2002239 ]
 [0.19713752 0.20111054 0.19744687 0.20397504 0.20033005]
 [0.20098244 0.19926758 0.19874884 0.20063293 0.20036823]
 [0.19769393 0.20035693 0.19719982 0.20474537 0.20000385]
 [0.19707067 0.19997805 0.19869012 0.203808   0.20045318]
 [0.19687994 0.20017053 0.19806956 0.2036991  0.20118093]
 [0.19885162 0.20045727 0.20015621 0.19885713 0.20167775]
 [0.19746265 0.20081837 0.19789597 0.20288205 0.20094095]
 [0.19691825 0.20017138 0.19884329 0.20396069 0.20010637]]
Rating
[4 4 4 1 4 4 4 5 4 4]


In [11]:
print(x_train)

[[   1   14   22 ...    0    0    0]
 [   1  194 1153 ...    0    0    0]
 [   1   14   47 ...    0    0    0]
 ...
 [   1   11    6 ...    0    0    0]
 [   1 1446 7079 ...    0    0    0]
 [   1   17    6 ...    0    0    0]]


In [12]:
print(x_train)

[[   1   14   22 ...    0    0    0]
 [   1  194 1153 ...    0    0    0]
 [   1   14   47 ...    0    0    0]
 ...
 [   1   11    6 ...    0    0    0]
 [   1 1446 7079 ...    0    0    0]
 [   1   17    6 ...    0    0    0]]


In [1]:
print(x_train)

NameError: name 'x_train' is not defined